<?php


// Translation of file /modules/tournament/admin/menu.inc

$_COS_LANG_MODULE['Admin (Search)'] = 'Admin (Search)';
$_COS_LANG_MODULE['Admin (Add)'] = 'Admin (Add)';

// Translation of file /modules/tournament/install.inc

$_COS_LANG_MODULE['Tourney overview'] = 'Tourney overview';
$_COS_LANG_MODULE['Gp-Lists'] = 'Gp-Lists';
$_COS_LANG_MODULE['Tournaments'] = 'Tournaments';
$_COS_LANG_MODULE['Reports'] = 'Reports';

// Translation of file /modules/tournament/lists/menu.inc

$_COS_LANG_MODULE['My lists'] = 'My lists';
$_COS_LANG_MODULE['Top lists'] = 'Top lists';
