<?php

$_COS_LANG_MODULE['Admin (Search)'] = 'Admin (Search)';
$_COS_LANG_MODULE['Admin (Add)'] = 'Admin (Legg til)';
$_COS_LANG_MODULE['Tourney overview'] = 'Tourney oversikt';
$_COS_LANG_MODULE['Gp-Lists'] = 'GP-Lister';
$_COS_LANG_MODULE['Tournaments'] = 'Turneringer';
$_COS_LANG_MODULE['Reports'] = 'Rapporter';
$_COS_LANG_MODULE['My lists'] = 'Mine lister';
$_COS_LANG_MODULE['Top lists'] = 'Topplister';
