<?php

$_COS_LANG_MODULE['Admin (Search)'] = 'Admin (Suchen)';
$_COS_LANG_MODULE['Admin (Add)'] = 'Admin (Add)';
$_COS_LANG_MODULE['Tourney overview'] = 'Tourney Überblick';
$_COS_LANG_MODULE['Gp-Lists'] = 'Gp-Listen';
$_COS_LANG_MODULE['Tournaments'] = 'Turniere';
$_COS_LANG_MODULE['Reports'] = 'Berichte';
$_COS_LANG_MODULE['My lists'] = 'Meine Listen';
$_COS_LANG_MODULE['Top lists'] = 'Top-Listen';
