<?php

$_COS_LANG_MODULE['Admin (Search)'] = 'Admin (Search)';
$_COS_LANG_MODULE['Admin (Add)'] = 'Admin (Lisää)';
$_COS_LANG_MODULE['Tourney overview'] = 'Turnaus yleiskatsaus';
$_COS_LANG_MODULE['Gp-Lists'] = 'Gp-listat';
$_COS_LANG_MODULE['Tournaments'] = 'Turnaukset';
$_COS_LANG_MODULE['Reports'] = 'Raportit';
$_COS_LANG_MODULE['My lists'] = 'Omat listat';
$_COS_LANG_MODULE['Top lists'] = 'Top-listat';
