<?php

    $_MODULE_MENU[] = array(
        'title' => lang::translate('Admin (Search)', null, array ('no_translate' => true)),
        'url' => '/tournament/admin/admin',
        'auth' => 'admin'
    );
    
    $_MODULE_MENU[] = array(
        'title' => lang::translate('Admin (Add)', null, array ('no_translate' => true)),
        'url' => '/tournament/admin/add',
        'auth' => 'admin'
    );

