<?php

$_COS_LANG_MODULE['Admin (Search)'] = 'Admin (Search)';
$_COS_LANG_MODULE['Admin (Add)'] = 'Admin (Lägg till)';
$_COS_LANG_MODULE['Tourney overview'] = 'Tourney översikt';
$_COS_LANG_MODULE['Gp-Lists'] = 'GP-listor';
$_COS_LANG_MODULE['Tournaments'] = 'Turneringar';
$_COS_LANG_MODULE['Reports'] = 'Rapporter';
$_COS_LANG_MODULE['My lists'] = 'Mina listor';
$_COS_LANG_MODULE['Top lists'] = 'Topplistor';
